### PR TITLE
fix: change type to avoid name conflict

### PR DESCRIPTION
**Pull request by huang-julien**
Hey :wave:

this PR fix the ci of https://github.com/nuxt/scripts/pull/176 . This is caused by a type GoogleTagManager and a var GoogleTagManager so it conflicts at build time. This PR renmae the type to GoogleTagManagerIsntance

### CODE REVIEW

**Comment by flashdesignory** [comment]
could you rename the type when importing? 

something like:
`import type { GoogleTagManager as GoogleTagManagerInstance } from 'third-party-capital';`

**Comment by huang-julien** [comment]
Do you mean in nuxt-script ? No because due to the name conflict, the type isn't exported in the build result

**Comment by flashdesignory** [comment]
> Do you mean in nuxt-script ? No because due to the name conflict, the type isn't exported in the build result

ah got it - that makes sense... I'll adjust

**Comment by huang-julien** [comment]
@flashdesignory google_tag_manager doesn't need to be removed from types i think

**Comment by flashdesignory** [comment]
closing, since this has been addressed with https://github.com/GoogleChromeLabs/third-party-capital/pull/54

**Pull request closed without merging**
