### PR TITLE
expose formatData and data objects

### PR DESCRIPTION
**Pull request by flashdesignory**
This pr exposes the formatData utils function in the build files as well as data objects for each wrapper.

@kara

### CODE REVIEW

**Review by huang-julien — APPROVED** [review]
thank you :heart: ! Seems like json are even correctly typed in the generated d.ts files !

**Comment by huang-julien** [comment]
fix #42

**Comment by flashdesignory** [comment]
update: exposing all utils functions that are exported now

**Review by kara — APPROVED** [review]
LGTM

**Pull request merged**
