### PR TITLE
Make datalayer name dynamic for GA & GTM

### PR DESCRIPTION
**Pull request by flashdesignory**
This makes dataLayerName required, but default values could be passed in from the wrappers.

example passing in 'GA-DataLayer' and 'GTM-DataLayer':

Screenshot 2024-07-16 at 11 27 56 AM

@kara

### CODE REVIEW

**Review by housseindjirdeh — APPROVED** [review]

**Comment by housseindjirdeh** [comment]
Thanks for this. We should probably start doing proper semver versioning when this lands

**Comment by flashdesignory** [comment]
it'll be a minor release.. it's already set up with semver:

`npm run release:minor`

**Review by huang-julien — COMMENTED** [review]
I think it would be a bit harder to correctly augment Window

How about accessing it through `window.dataLayers[dataLayername]` ?

**Comment by flashdesignory** [comment]
> I think it would be a bit harder to correctly augment Window
> 
> How about accessing it through `window.dataLayers[dataLayername]` ?

Made the change, please review @huang-julien @housseindjirdeh

**Review by housseindjirdeh — APPROVED** [review]

**Pull request merged**
